<?php

include_once 'loop_book.features.inc';

include_once drupal_get_path('module', 'loop_book') . '/lib/src/Book.php';
use Drupal\loop_book\Book;

function loop_book_get_tree($node) {
  $book = new Book();

  $tree = $book->getTree($node->nid);

  return $tree;
}

function loop_book_get_roots($node) {
  $book = new Book();

  $roots = $book->getRoots($node->nid);

  return $roots;
}

function loop_book_node_update($node) {
  $field = field_info_instance('node', 'field_loop_book_children', $node->type);
  if ($field) {
    $book = Book::getInstance();
    $book->rebuild();
  }
}
